/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AdminCommon;
import io.swagger.client.model.AdminEmailPassResetInfo;
import io.swagger.client.model.Body4;
import io.swagger.client.model.CommonErrorResp;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse409;
import io.swagger.client.model.UserResp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Ignore
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    /**
     * Get Admin list
     *
     * Get Admin List.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminsGetTest() throws ApiException {
        Integer filter = null;
        List<AdminCommon> response = api.adminsGet(filter);

        // TODO: test validations
    }
    /**
     * Check if Password can be reset for Admin
     *
     * Check for Password Reset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminsPassResetPostTest() throws ApiException {
        AdminEmailPassResetInfo body = null;
        UserResp response = api.adminsPassResetPost(body);

        // TODO: test validations
    }
    /**
     * Add Admin operation
     *
     * Add Admin.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminsPostTest() throws ApiException {
        Body4 body = null;
        InlineResponse200 response = api.adminsPost(body);

        // TODO: test validations
    }
}
