/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BusinessTypeNotFoundResp;
import io.swagger.client.model.BusinessTypeReq;
import io.swagger.client.model.BusinessTypeResp;
import io.swagger.client.model.CommonErrorResp;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BusinessTypesApi
 */
@Ignore
public class BusinessTypesApiTest {

    private final BusinessTypesApi api = new BusinessTypesApi();

    /**
     * To Delte Existing Business Types
     *
     * Delete Business Type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void businessTypesBusinessTypeIdDeleteTest() throws ApiException {
        Long businessTypeId = null;
        Integer adminId = null;
        BusinessTypeResp response = api.businessTypesBusinessTypeIdDelete(businessTypeId, adminId);

        // TODO: test validations
    }
    /**
     * To Update the Business Types
     *
     * Update Business Type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void businessTypesBusinessTypeIdPutTest() throws ApiException {
        BusinessTypeReq body = null;
        Long businessTypeId = null;
        BusinessTypeResp response = api.businessTypesBusinessTypeIdPut(body, businessTypeId);

        // TODO: test validations
    }
    /**
     * Get All Business Types
     *
     * Get Business Types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void businessTypesGetTest() throws ApiException {
        InlineResponse2002 response = api.businessTypesGet();

        // TODO: test validations
    }
    /**
     * Add new Business Type
     *
     * Add Business Type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void businessTypesPostTest() throws ApiException {
        BusinessTypeReq body = null;
        BusinessTypeResp response = api.businessTypesPost(body);

        // TODO: test validations
    }
}
