/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body5;
import io.swagger.client.model.CommonErrorResp;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse409;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeeApi
 */
@Ignore
public class EmployeeApiTest {

    private final EmployeeApi api = new EmployeeApi();

    /**
     * Add Employee operation
     *
     * Add Employee.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesPostTest() throws ApiException {
        Body5 body = null;
        InlineResponse200 response = api.employeesPost(body);

        // TODO: test validations
    }
}
