/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body6;
import io.swagger.client.model.Body7;
import io.swagger.client.model.InlineResponse2007;
import io.swagger.client.model.InlineResponse2008;
import io.swagger.client.model.InlineResponse2009;
import io.swagger.client.model.InlineResponse4002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    /**
     * Get Existing Groups
     *
     * Get Existing Groups
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGetTest() throws ApiException {
        InlineResponse2007 response = api.groupsGet();

        // TODO: test validations
    }
    /**
     * Delete Existing Group
     *
     * Delete Group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupIdDeleteTest() throws ApiException {
        Long groupId = null;
        InlineResponse2009 response = api.groupsGroupIdDelete(groupId);

        // TODO: test validations
    }
    /**
     * Add Users to the Group
     *
     * Add User to group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupIdUsersPostTest() throws ApiException {
        Body7 body = null;
        Long groupId = null;
        InlineResponse2009 response = api.groupsGroupIdUsersPost(body, groupId);

        // TODO: test validations
    }
    /**
     * Add New  Groups
     *
     * Add Groups
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsPostTest() throws ApiException {
        Body6 body = null;
        InlineResponse2008 response = api.groupsPost(body);

        // TODO: test validations
    }
}
