/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CommonErrorResp;
import io.swagger.client.model.InlineResponse404;
import io.swagger.client.model.MobileNoExistsResp;
import io.swagger.client.model.OtpPassResetResp;
import io.swagger.client.model.OtpReq;
import io.swagger.client.model.OtpResp;
import io.swagger.client.model.PassResetOtpReq;
import io.swagger.client.model.VerifyOtpReq;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OtpApi
 */
@Ignore
public class OtpApiTest {

    private final OtpApi api = new OtpApi();

    /**
     * The operation for password reset otp
     *
     * Password reset OTP.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void otpPassresetotpPostTest() throws ApiException {
        PassResetOtpReq body = null;
        OtpPassResetResp response = api.otpPassresetotpPost(body);

        // TODO: test validations
    }
    /**
     * The operation creates a otp and sends it to the client
     *
     * Generate OTP.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void otpPostTest() throws ApiException {
        OtpReq body = null;
        OtpResp response = api.otpPost(body);

        // TODO: test validations
    }
    /**
     * The operation veify the otp enterred by the userr
     *
     * Verify OTP.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void otpVerifyPostTest() throws ApiException {
        VerifyOtpReq body = null;
        OtpResp response = api.otpVerifyPost(body);

        // TODO: test validations
    }
}
