/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CommonErrorResp;
import io.swagger.client.model.CommonResp;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.RoleExistsResp;
import io.swagger.client.model.RoleReq;
import io.swagger.client.model.RoleResp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RolesApi
 */
@Ignore
public class RolesApiTest {

    private final RolesApi api = new RolesApi();

    /**
     * Get All Roles
     *
     * Get Roles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesGetTest() throws ApiException {
        Boolean deleted = null;
        InlineResponse2003 response = api.rolesGet(deleted);

        // TODO: test validations
    }
    /**
     * Add new Role
     *
     * Add Role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesPostTest() throws ApiException {
        RoleReq body = null;
        RoleResp response = api.rolesPost(body);

        // TODO: test validations
    }
    /**
     * Delete existing Role
     *
     * Delete Role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesRoleIdDeleteTest() throws ApiException {
        Long roleId = null;
        Long adminId = null;
        RoleResp response = api.rolesRoleIdDelete(roleId, adminId);

        // TODO: test validations
    }
    /**
     * Update existing Role
     *
     * Update Role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesRoleIdPostTest() throws ApiException {
        RoleReq body = null;
        Long roleId = null;
        RoleResp response = api.rolesRoleIdPost(body, roleId);

        // TODO: test validations
    }
}
