/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Body2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class Body2 {
  @SerializedName("inviteUsers")
  private List<String> inviteUsers = null;

  public Body2 inviteUsers(List<String> inviteUsers) {
    this.inviteUsers = inviteUsers;
    return this;
  }

  public Body2 addInviteUsersItem(String inviteUsersItem) {
    if (this.inviteUsers == null) {
      this.inviteUsers = new ArrayList<String>();
    }
    this.inviteUsers.add(inviteUsersItem);
    return this;
  }

   /**
   * Get inviteUsers
   * @return inviteUsers
  **/
  @Schema(description = "")
  public List<String> getInviteUsers() {
    return inviteUsers;
  }

  public void setInviteUsers(List<String> inviteUsers) {
    this.inviteUsers = inviteUsers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return Objects.equals(this.inviteUsers, body2.inviteUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inviteUsers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("    inviteUsers: ").append(toIndentedString(inviteUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
