/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class Body1 {
  @SerializedName("currentPin")
  private String currentPin = null;

  @SerializedName("newPin")
  private String newPin = null;

  @SerializedName("confirmPin")
  private String confirmPin = null;

  public Body1 currentPin(String currentPin) {
    this.currentPin = currentPin;
    return this;
  }

   /**
   * Get currentPin
   * @return currentPin
  **/
  @Schema(required = true, description = "")
  public String getCurrentPin() {
    return currentPin;
  }

  public void setCurrentPin(String currentPin) {
    this.currentPin = currentPin;
  }

  public Body1 newPin(String newPin) {
    this.newPin = newPin;
    return this;
  }

   /**
   * Get newPin
   * @return newPin
  **/
  @Schema(required = true, description = "")
  public String getNewPin() {
    return newPin;
  }

  public void setNewPin(String newPin) {
    this.newPin = newPin;
  }

  public Body1 confirmPin(String confirmPin) {
    this.confirmPin = confirmPin;
    return this;
  }

   /**
   * Get confirmPin
   * @return confirmPin
  **/
  @Schema(required = true, description = "")
  public String getConfirmPin() {
    return confirmPin;
  }

  public void setConfirmPin(String confirmPin) {
    this.confirmPin = confirmPin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return Objects.equals(this.currentPin, body1.currentPin) &&
        Objects.equals(this.newPin, body1.newPin) &&
        Objects.equals(this.confirmPin, body1.confirmPin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPin, newPin, confirmPin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("    currentPin: ").append(toIndentedString(currentPin)).append("\n");
    sb.append("    newPin: ").append(toIndentedString(newPin)).append("\n");
    sb.append("    confirmPin: ").append(toIndentedString(confirmPin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
