/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class InlineResponse2001Data {
  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("mpinModifiedDatetime")
  private String mpinModifiedDatetime = null;

  public InlineResponse2001Data userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public InlineResponse2001Data mpinModifiedDatetime(String mpinModifiedDatetime) {
    this.mpinModifiedDatetime = mpinModifiedDatetime;
    return this;
  }

   /**
   * Get mpinModifiedDatetime
   * @return mpinModifiedDatetime
  **/
  @Schema(description = "")
  public String getMpinModifiedDatetime() {
    return mpinModifiedDatetime;
  }

  public void setMpinModifiedDatetime(String mpinModifiedDatetime) {
    this.mpinModifiedDatetime = mpinModifiedDatetime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Data inlineResponse2001Data = (InlineResponse2001Data) o;
    return Objects.equals(this.userId, inlineResponse2001Data.userId) &&
        Objects.equals(this.mpinModifiedDatetime, inlineResponse2001Data.mpinModifiedDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, mpinModifiedDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Data {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    mpinModifiedDatetime: ").append(toIndentedString(mpinModifiedDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
