/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse4001Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class InlineResponse4001Data {
  @SerializedName("details")
  private String details = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("upgradeRole")
  private String upgradeRole = null;

  public InlineResponse4001Data details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public InlineResponse4001Data role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @Schema(description = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public InlineResponse4001Data upgradeRole(String upgradeRole) {
    this.upgradeRole = upgradeRole;
    return this;
  }

   /**
   * Get upgradeRole
   * @return upgradeRole
  **/
  @Schema(description = "")
  public String getUpgradeRole() {
    return upgradeRole;
  }

  public void setUpgradeRole(String upgradeRole) {
    this.upgradeRole = upgradeRole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4001Data inlineResponse4001Data = (InlineResponse4001Data) o;
    return Objects.equals(this.details, inlineResponse4001Data.details) &&
        Objects.equals(this.role, inlineResponse4001Data.role) &&
        Objects.equals(this.upgradeRole, inlineResponse4001Data.upgradeRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, role, upgradeRole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4001Data {\n");
    
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    upgradeRole: ").append(toIndentedString(upgradeRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
