/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * KycDocsInput
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class KycDocsInput {
  @SerializedName("idProofFile")
  private String idProofFile = null;

  @SerializedName("passportPhoto")
  private String passportPhoto = null;

  @SerializedName("businessProof")
  private String businessProof = null;

  public KycDocsInput idProofFile(String idProofFile) {
    this.idProofFile = idProofFile;
    return this;
  }

   /**
   * Get idProofFile
   * @return idProofFile
  **/
  @Schema(description = "")
  public String getIdProofFile() {
    return idProofFile;
  }

  public void setIdProofFile(String idProofFile) {
    this.idProofFile = idProofFile;
  }

  public KycDocsInput passportPhoto(String passportPhoto) {
    this.passportPhoto = passportPhoto;
    return this;
  }

   /**
   * Get passportPhoto
   * @return passportPhoto
  **/
  @Schema(description = "")
  public String getPassportPhoto() {
    return passportPhoto;
  }

  public void setPassportPhoto(String passportPhoto) {
    this.passportPhoto = passportPhoto;
  }

  public KycDocsInput businessProof(String businessProof) {
    this.businessProof = businessProof;
    return this;
  }

   /**
   * Get businessProof
   * @return businessProof
  **/
  @Schema(description = "")
  public String getBusinessProof() {
    return businessProof;
  }

  public void setBusinessProof(String businessProof) {
    this.businessProof = businessProof;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KycDocsInput kycDocsInput = (KycDocsInput) o;
    return Objects.equals(this.idProofFile, kycDocsInput.idProofFile) &&
        Objects.equals(this.passportPhoto, kycDocsInput.passportPhoto) &&
        Objects.equals(this.businessProof, kycDocsInput.businessProof);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idProofFile, passportPhoto, businessProof);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KycDocsInput {\n");
    
    sb.append("    idProofFile: ").append(toIndentedString(idProofFile)).append("\n");
    sb.append("    passportPhoto: ").append(toIndentedString(passportPhoto)).append("\n");
    sb.append("    businessProof: ").append(toIndentedString(businessProof)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
