/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * KycUpdateInput
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class KycUpdateInput {
  @SerializedName("mobilePhone")
  private String mobilePhone = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("photoIdProof")
  private Integer photoIdProof = null;

  @SerializedName("photoId")
  private String photoId = null;

  @SerializedName("businessProof")
  private String businessProof = null;

  @SerializedName("photo")
  private String photo = null;

  @SerializedName("otp")
  private String otp = null;

  public KycUpdateInput mobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * Get mobilePhone
   * @return mobilePhone
  **/
  @Schema(description = "")
  public String getMobilePhone() {
    return mobilePhone;
  }

  public void setMobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
  }

  public KycUpdateInput email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public KycUpdateInput photoIdProof(Integer photoIdProof) {
    this.photoIdProof = photoIdProof;
    return this;
  }

   /**
   * Get photoIdProof
   * @return photoIdProof
  **/
  @Schema(description = "")
  public Integer getPhotoIdProof() {
    return photoIdProof;
  }

  public void setPhotoIdProof(Integer photoIdProof) {
    this.photoIdProof = photoIdProof;
  }

  public KycUpdateInput photoId(String photoId) {
    this.photoId = photoId;
    return this;
  }

   /**
   * Get photoId
   * @return photoId
  **/
  @Schema(description = "")
  public String getPhotoId() {
    return photoId;
  }

  public void setPhotoId(String photoId) {
    this.photoId = photoId;
  }

  public KycUpdateInput businessProof(String businessProof) {
    this.businessProof = businessProof;
    return this;
  }

   /**
   * Get businessProof
   * @return businessProof
  **/
  @Schema(description = "")
  public String getBusinessProof() {
    return businessProof;
  }

  public void setBusinessProof(String businessProof) {
    this.businessProof = businessProof;
  }

  public KycUpdateInput photo(String photo) {
    this.photo = photo;
    return this;
  }

   /**
   * Get photo
   * @return photo
  **/
  @Schema(description = "")
  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public KycUpdateInput otp(String otp) {
    this.otp = otp;
    return this;
  }

   /**
   * Get otp
   * @return otp
  **/
  @Schema(description = "")
  public String getOtp() {
    return otp;
  }

  public void setOtp(String otp) {
    this.otp = otp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KycUpdateInput kycUpdateInput = (KycUpdateInput) o;
    return Objects.equals(this.mobilePhone, kycUpdateInput.mobilePhone) &&
        Objects.equals(this.email, kycUpdateInput.email) &&
        Objects.equals(this.photoIdProof, kycUpdateInput.photoIdProof) &&
        Objects.equals(this.photoId, kycUpdateInput.photoId) &&
        Objects.equals(this.businessProof, kycUpdateInput.businessProof) &&
        Objects.equals(this.photo, kycUpdateInput.photo) &&
        Objects.equals(this.otp, kycUpdateInput.otp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mobilePhone, email, photoIdProof, photoId, businessProof, photo, otp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KycUpdateInput {\n");
    
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    photoIdProof: ").append(toIndentedString(photoIdProof)).append("\n");
    sb.append("    photoId: ").append(toIndentedString(photoId)).append("\n");
    sb.append("    businessProof: ").append(toIndentedString(businessProof)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
