/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OtpRespData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class OtpRespData {
  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("mobileNumber")
  private String mobileNumber = null;

  @SerializedName("otpValidationStatus")
  private String otpValidationStatus = null;

  public OtpRespData userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public OtpRespData mobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Get mobileNumber
   * @return mobileNumber
  **/
  @Schema(description = "")
  public String getMobileNumber() {
    return mobileNumber;
  }

  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }

  public OtpRespData otpValidationStatus(String otpValidationStatus) {
    this.otpValidationStatus = otpValidationStatus;
    return this;
  }

   /**
   * Get otpValidationStatus
   * @return otpValidationStatus
  **/
  @Schema(example = "Pending", description = "")
  public String getOtpValidationStatus() {
    return otpValidationStatus;
  }

  public void setOtpValidationStatus(String otpValidationStatus) {
    this.otpValidationStatus = otpValidationStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtpRespData otpRespData = (OtpRespData) o;
    return Objects.equals(this.userId, otpRespData.userId) &&
        Objects.equals(this.mobileNumber, otpRespData.mobileNumber) &&
        Objects.equals(this.otpValidationStatus, otpRespData.otpValidationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, mobileNumber, otpValidationStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtpRespData {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("    otpValidationStatus: ").append(toIndentedString(otpValidationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
