/*
 * UserManagementAPI
 * API for user management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@naqdina.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PinReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-22T21:50:37.996Z[GMT]")
public class PinReq {
  @SerializedName("pin")
  private String pin = null;

  @SerializedName("confirmPin")
  private String confirmPin = null;

  public PinReq pin(String pin) {
    this.pin = pin;
    return this;
  }

   /**
   * Get pin
   * @return pin
  **/
  @Schema(required = true, description = "")
  public String getPin() {
    return pin;
  }

  public void setPin(String pin) {
    this.pin = pin;
  }

  public PinReq confirmPin(String confirmPin) {
    this.confirmPin = confirmPin;
    return this;
  }

   /**
   * Get confirmPin
   * @return confirmPin
  **/
  @Schema(required = true, description = "")
  public String getConfirmPin() {
    return confirmPin;
  }

  public void setConfirmPin(String confirmPin) {
    this.confirmPin = confirmPin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PinReq pinReq = (PinReq) o;
    return Objects.equals(this.pin, pinReq.pin) &&
        Objects.equals(this.confirmPin, pinReq.confirmPin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pin, confirmPin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PinReq {\n");
    
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    confirmPin: ").append(toIndentedString(confirmPin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
